### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by lgo** [keriwarr/orangejoos#21]
- [ ] Clean up the AST
  - [ ] Pointer to parent node (easy to implement with a visitor, if you're ok with `#parent` being nilable)
  - [ ] expr not subclass of stmt
  - [x] re-visit modifiers, make them a string instead and remove the AST
  - [x] destroy TMPMethodDecl
  - [ ] make `AST::Param` wrap an `AST::VariableDecl`
  - [ ] exprop -> abstract, unaryop class, binaryop class
  - [ ] squish `AST::FieldDeclStmt` with `AST::FieldDecl` and `AST::VarDeclStmt`

 - [ ] Flatten some nodes
   - [ ] DeclStmt and FieldDecl. These have similar contents, so maybe they can just be merged.
   - [ ] File and PackageDecl.

- [x] Clean up variable and class names, e.g. `ExprClassInit` and `ExprArrayCreation` are inconsistent. `Typing::Types::Reference` should be `Typing::Types::Instance`

- [ ] Rip out common logic like types. Can we make declaration `to_type` shared?

- [x] Write an actual AST print. Being able to see the AST 1:1 of the actual tree would be so helpful. (edited)
  - visitor

- [x] Dealing with RHS variables. Do we also wrap then with a Variable node?

- [ ] figure out how to deal with complicated fields it method invocations. E.g. `(variable.GetThing()).x.y`, what is that in the parse tree or AST and how do we fix or handle it.

- [ ] Coming up with well-defined subsystems. Like what I started with `Typing` that is included.

- [ ] Clean up the file structure. Probably breaking out some things into folders for the subsystems. Name resolution is a bit long and very messy

- [x] Clean up Crystal-isms. e.g. `<Type> | Nil` => `<Type>?`

- [ ] A way to make sure that Visitor has methods for all AST nodes?

- [ ] precompute/cache class hierarchy relationships (implements/extends)

- [ ] Make operators ENUMs instead of strings

- [ ] Correctly implement `Lexeme#to_s`

- [ ] Can we change Simplification so that `AST::Name`s don't have to be returned as `AST::ExprRef`s?

- [ ] Visitor cleanup
  - Is there any way we can have guarantees that visitors which need to be run in a certain order, are?
  - Is there any way we can have guarantees that certain visitors don't need to be run in a certain order?
  - Can we clean up visitor.cr?
    - [ ] Move call to `ast_children` to accept method?
    - [ ] Define super method on `AST::Node` instead of every concrete node
    - [ ] return true false + explicit recursion on children?
    - [ ] borrow ideas from crystals visitor?

- [ ] We probably don't understand ambiguous names fully. Need to do a read of the JLS (6.5) and re-visit name resolution

There's also the argument of trying to either rip out the logic for all of one sub-system (e.g. pretty printing) to one file or keeping it all in one.

It's currently pretty messy and longer so I'm actually leaning towards ripping it out. My biggest concern is that you now have to reference two files at all times. The pro is it's much easier to navigate the raw AST structure.
