### ISSUE TITLE
A2 Spec and Requirements

### ISSUE THREAD

**Issue by lgo** [keriwarr/orangejoos#23]
### Legend:
*[X]* denotes a feature we may not need to implement for future assignments.
- [ ] denotes a task that needs to be done
- [x] denotes a task that is complete

### From Asst

- [x] No two fields declared in the same class may have the same name.
- [x] No two local variables with overlapping scope have the same name.
- [x] No two classes or interfaces have the same canonical name.
- [ ] No single-type-import declaration clashes with the class or interface declared in the same file.
- [ ] No two single-type-import declarations clash with each other.
- [x] All type names must resolve to some class or interface declared in some file listed on the Joos command line.
- [x] All simple type names must resolve to a unique class or interface.
- [ ] When a fully qualified name resolves to a type, no strict prefix of the fully qualified name can resolve to a type in the same environment.
- [x] No package names or prefixes of package names of declared packages, single-type-import declarations or import-on-demand declarations that are used may resolve to types, except for types in the default package.
- [x] Every import-on-demand declaration must refer to a package declared in some file listed on the Joos command line. That is, the import-on-demand declaration must refer to a package whose name appears as the package declaration in some source file, or whose name is a prefix of the name appearing in some package declaration.
- [x] A class must not extend an interface. (JLS 8.1.3, dOvs simple constraint 1)
- [x] A class must not implement a class. (JLS 8.1.4, dOvs simple constraint 2)
- [ ] An interface must not be repeated in an implements clause, or in an extends clause of an interface. (JLS 8.1.4, dOvs simple constraint 3)
- [x] A class must not extend a final class. (JLS 8.1.1.2, 8.1.3, dOvs simple constraint 4)
- [x] An interface must not extend a class. (JLS 9.1.2)
- [x] The hierarchy must be acyclic. (JLS 8.1.3, 9.1.2, dOvs well-formedness constraint 1)
- [x] A class or interface must not declare two methods with the same signature (name and parameter types). (JLS 8.4, 9.4, dOvs well-formedness constraint 2)
- [x] A class must not declare two constructors with the same parameter types (dOvs 8.8.2, simple constraint 5)
- [x] A class or interface must not contain (declare or inherit) two methods with the same signature but different return types (JLS 8.1.1.1, 8.4, 8.4.2, 8.4.6.3, 8.4.6.4, 9.2, 9.4.1, dOvs well-formedness constraint 3)
- [x] A class that contains (declares or inherits) any abstract methods must be abstract. (JLS 8.1.1.1, well-formedness constraint 4)
- [x] A nonstatic method must not replace a static method (JLS 8.4.6.1, dOvs well-formedness constraint 5)
- [x] A method must not replace a method with a different return type. (JLS 8.1.1.1, 8.4, 8.4.2, 8.4.6.3, 8.4.6.4, 9.2, 9.4.1, dOvs well-formedness constraint 6)
- [x] A protected method must not replace a public method. (JLS 8.4.6.3, dOvs well-formedness constraint 7)
- [x] A method must not replace a final method. (JLS 8.4.3.3, dOvs well-formedness constraint 9)

### Other
- [x] Just calling this out now: during name resolution I think we need to assert that if it is ExprRef, then the reference must resolve to a Class or Interface.
- [x] Traverse tree, resolve any ExprThis to the context's class type.
- [x] Traverse tree, resolve any type's to their names.

There is a problem where super_methods of a class returns all the methods that are inherited squished in to one namespace. The hierarchy information is thus lost. Fixing this is necessary to fix:
- `pub/assignment_testcases/a2/Je_4_AbstractMethod_AbstractObjectMethods`
- `pub/assignment_testcases/a2/Je_4_InheritShadowsNonabstract`
- `pub/assignment_testcases/a2/Je_4_ProtectedOverride_Exception_Clone`
- `pub/assignment_testcases/a2/Je_4_ProtectedOverride_FromSuperclassAndInterface`
