### ISSUE TITLE
Optional optimizations (i.e. after A4)

### ISSUE THREAD

**Issue by keriwarr** [keriwarr/orangejoos#24]
- [ ] Modify visitor as follows:
  - Change the signature of visit to `visit(AST::FooNode node) : Boolean`
  - Recurse on children if visit returns true
  - Do not recurse otherwise
  - This could be implemented in the accept function on nodes
- [ ] `<Type> | Nil` -> `<Type>?`
- [ ] A way to make sure that Visitor has methods for all AST nodes?
- [ ] Escape string and character literals when pretty printing
