### ISSUE TITLE
For-fun Improvements (i.e. not gunna happen)

### ISSUE THREAD

**Issue by keriwarr** [keriwarr/orangejoos#36]
- [ ] Make the source code a CST, i.e. include whitespace tokens and make the code reproducible from the AST
- [ ] Modify visitor as follows:
  - Change the signature of visit to visit(AST::FooNode node) : Boolean
  - Recurse on children if visit returns true
  - Do not recurse otherwise
  - This could be implemented in the accept function on nodes
- [ ] Add DWARF debug symbols to generated code
- [ ] Escape string and char literals when pretty printing
- [ ] Replace `has_modifier("<modifier>") with a series of methods of the form `is_<modifier>`
- [ ] Enumerate parse node names (due to reuse).
- [ ] Why are the JLALR java files being compiled on marmoset?
- [ ] Exit code improvements
  - Use different exit codes for different failures (iff not marmoset?)
  - Exit differently if an unexpected kind of exception is raised during a given stage
- [ ] Consider using StringScanner during scanning to store Lexemes
