### ISSUE TITLE
A3 Spec and Requirements

### ISSUE THREAD

**Issue by keriwarr** [keriwarr/orangejoos#37]
### Legend:
*[X]* denotes a feature we may not need to implement for future assignments.
- [ ] denotes a task that needs to be done
- [x] denotes a task that is complete

### Type checking
- [x] Handle method call type resolution
- [x] Handle field type resolution
- [x] Handle array type resolution
- [x] Handle method overloading (and generally signature matching)
- [ ] Ensure all Java expression rules exist (integers/numbers, bools, chars)
- *[X]* Check for protected accesses.
- *[X]* Super classes require a zero-argument constructor
- *[X]* No abstract classes are initialized
- [x] No "this" variable or field access in static methods or static field initializers (normally, those are implicitly allowed).
- [x] No non-static "this" method calls from a static method.
- [ ] Verify the implicit casting of numerical types (do they cast in methods? do they case in expressions? do they cast in assignments?)
