### ISSUE TITLE
A4 Spec and Requirements

### ISSUE THREAD

**Issue by keriwarr** [keriwarr/orangejoos#38]
### Legend:
*[X]* denotes a feature we may not need to implement for future assignments.
- [ ] denotes a task that needs to be done
- [x] denotes a task that is complete

### Reachability
- [x] Constant reduction
  - [ ] reduction across variables
- [x] Only allow reachable statements (if/else, for, while). See section 14.20 of the JLS.
- [ ] Every local variable must have an initializer without itself.
- [x] The last statement of all reachable paths must be a return.
