### ISSUE TITLE
A1 Spec and Requirements

### ISSUE THREAD

**Issue by keriwarr** [keriwarr/orangejoos#39]
### Legend:
*[X]* denotes a feature we may not need to implement for future assignments.
- [ ] denotes a task that needs to be done
- [x] denotes a task that is complete

From the specification:

- [ ] Check for the existance of a main function and the correct
  signature.
- [x] Check the size of numbers are valid.
- [x] Check the length of character literals (should happen in
  scanning).
- ~[ ] Repeated function definitions.~ Doing this during name resolution?
- Refer to the JLS1 spec to find more rules.
